// API 响应类型

export interface ApiResponse<T = unknown> {
  code: number;
  message: string;
  data: T;
}

export interface ApiError {
  code: number;
  message: string;
  details?: unknown;
}

export interface PaginatedResponse<T> {
  list: T[];
  total: number;
  page: number;
  limit: number;
}

export interface LoginResponse {
  token: string;
  user: {
    id: string;
    username: string;
    name: string;
    roleCode: 'admin' | 'leader' | 'user';
    roleId: string;
    companyId?: string;
  };
}

// 消息相关
export interface Notification {
  id: string;
  userId: string;
  type: 'task' | 'approval' | 'reminder';
  title: string;
  content: string;
  isRead: boolean;
  readAt: string | null;
  createdAt: string;
}

export interface NotificationListResponse {
  list: Notification[];
  total: number;
  unreadCount: number;
}

// 部门相关
export interface Department {
  id: string;
  code: string;
  name: string;
  managerId: string | null;
  manager?: {
    id: string;
    username: string;
    name: string;
    status: 'active' | 'inactive';
    roleId?: string | null;
    roleObj?: { id: string; code: string; name: string } | null;
  } | null;
  status: 'active' | 'inactive';
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
}

export interface DepartmentListResponse {
  list: Department[];
  total: number;
}

// Document approval contracts now live in unified approval; document numbers
// are generated by the server-side default rule service. No legacy shared
// approval or user-configurable numbering interfaces are exported here.

// 操作日志
export interface OperationLog {
  id: string;
  userId: string;
  userName?: string;
  action: string;
  module: string;
  objectId: string;
  objectType: string;
  details: Record<string, unknown> | null;
  ip: string;
  createdAt: string;
}

export interface OperationLogListResponse {
  list: OperationLog[];
  total: number;
}
