import { ModuleKey } from '../../../shared/decorators/module-key.decorator';
import { Controller, Get, Param, UseGuards } from '@nestjs/common';
import { BatchMaterialUsageService } from '../services/batch-material-usage.service';
import { JwtAuthGuard } from '../../auth/jwt-auth.guard';

// BatchMaterialUsage is internal-only: it is auto-generated by the mixing
// trace bridge (BatchMaterialUsageService.createFromMixingLine). No public
// manual create/update route is exposed; only read queries below.
@ModuleKey('traceability_batch')
@Controller('batch-trace')
@UseGuards(JwtAuthGuard)
export class BatchMaterialUsageController {
  constructor(private readonly batchMaterialUsageService: BatchMaterialUsageService) {}

  @Get('batch-material-usage/production-batches/:id/materials')
  getProductionBatchMaterials(@Param('id') id: string) {
    return this.batchMaterialUsageService.getProductionBatchMaterials(id);
  }

  @Get('material-batches/:id/usages')
  getMaterialBatchUsages(@Param('id') id: string) {
    return this.batchMaterialUsageService.getMaterialBatchUsages(id);
  }
}
