import { ModuleKey } from '../../../shared/decorators/module-key.decorator';
import { Controller, Get, Delete, Param, Query, UseGuards } from '@nestjs/common';
import { ApiTags, ApiOperation, ApiBearerAuth, ApiResponse } from '@nestjs/swagger';
import { MaterialUsageService } from '../services/material-usage.service';
import { QueryMaterialUsageDto } from '../dto/material-usage.dto';
import { JwtAuthGuard } from '../../auth/jwt-auth.guard';
import { RolesGuard } from '../../../common/guards/roles.guard';

// Manual create/update of BatchMaterialUsage is intentionally NOT exposed:
// usage records are auto-generated by the mixing trace bridge. Only read
// queries and cleanup-delete remain on the public surface.
@ApiTags('批次物料关联管理')
@ModuleKey('traceability_batch')
@Controller('batch-trace/material-usage')
@UseGuards(JwtAuthGuard, RolesGuard)
@ApiBearerAuth()
export class MaterialUsageController {
  constructor(private readonly service: MaterialUsageService) {}

  @Get()
  @ApiOperation({ summary: '查询生产批次使用的原料' })
  @ApiResponse({ status: 200, description: '查询成功' })
  findByProductionBatch(@Query() query: QueryMaterialUsageDto) {
    return this.service.findByProductionBatch(query.productionBatchId);
  }

  @Delete(':id')
  @ApiOperation({ summary: '删除批次物料关联' })
  @ApiResponse({ status: 200, description: '删除成功' })
  @ApiResponse({ status: 404, description: '关联记录不存在' })
  remove(@Param('id') id: string) {
    return this.service.remove(id);
  }
}
