import type { RegistryConfig } from './module-route-registry';

export const REGISTRY_CONFIG: RegistryConfig = {
  public: [
    { path: 'auth', mode: 'prefix' },
    { path: 'liveness', mode: 'exact' },
    { path: 'module-access', mode: 'exact' },
  ],
  adminOnly: [
    { path: 'users', mode: 'exact' },
    { path: 'departments', mode: 'exact' },
    { path: 'roles', mode: 'exact' },
    { path: 'admin/module-access', mode: 'exact' },
    { path: 'audit', mode: 'exact' },
    { path: 'operation-logs', mode: 'exact' },
    { path: 'system-configs', mode: 'exact' },
    { path: 'permission-audit-logs', mode: 'exact' },
    { path: 'org-bootstrap', mode: 'exact' },
    { path: 'companies', mode: 'exact' },
    // 旧权限子系统（Task 22 删除前暂留）
    { path: 'permissions', mode: 'exact' },
    { path: 'fine-grained-permissions', mode: 'exact' },
    { path: 'department-permissions', mode: 'exact' },
    { path: 'user-permissions', mode: 'exact' },
  ],
  auxiliary: [
    { path: 'notifications', mode: 'exact', guard: 'authenticated' },
    { path: 'upload', mode: 'exact', guard: 'authenticated' },
    { path: 'search', mode: 'exact', guard: 'authenticated' },
  ],
  modules: {
    work_execution: [
      { path: 'todos', mode: 'exact' },
      { path: 'tasks', mode: 'exact' },
      { path: 'approval-tasks', mode: 'exact' },
      { path: 'approval-instances', mode: 'exact' },
      { path: 'record-task-assignments', mode: 'exact' },
      { path: 'record-task-instances', mode: 'exact' },
    ],
    document_approval: [
      { path: 'documents', mode: 'exact' },
      { path: 'templates', mode: 'exact' },
      { path: 'approval-definitions', mode: 'exact' },
      { path: 'dynamic-forms', mode: 'exact' },
      { path: 'record-templates', mode: 'exact' },
      { path: 'records', mode: 'exact' },
    ],
    production_execution: [
      { path: 'batch-trace/production-batches', mode: 'exact' },
      { path: 'production-runs', mode: 'exact' },
      { path: 'mixing', mode: 'exact' },
      { path: 'batch-trace/batch-mixing-aggregations', mode: 'exact' },
      { path: 'process/instances', mode: 'exact' },
      { path: 'process/templates', mode: 'exact' },
      { path: 'process-steps', mode: 'exact' },
      { path: 'process-records', mode: 'exact' },
      { path: 'shift-instances', mode: 'exact' },
      { path: 'team-shifts', mode: 'exact' },
      { path: 'line-change-check-records', mode: 'exact' },
      { path: 'production-plans', mode: 'exact' },
    ],
    product_rd: [
      { path: 'products', mode: 'exact' },
      { path: 'recipes', mode: 'exact' },
      { path: 'model-landing', mode: 'exact' },
      { path: 'change-events', mode: 'exact' },
      { path: 'change-verification-records', mode: 'exact' },
      { path: 'change-compliance-records', mode: 'exact' },
      { path: 'product-process-changes', mode: 'exact' },
    ],
    quality_compliance: [
      { path: 'non-conformances', mode: 'exact' },
      { path: 'corrective-actions', mode: 'exact' },
      { path: 'product-recalls', mode: 'exact' },
      { path: 'customer-complaints', mode: 'exact' },
      { path: 'deviation-reports', mode: 'exact' },
      { path: 'deviation-analytics', mode: 'exact' },
      { path: 'supplier-evaluations', mode: 'exact' },
      { path: 'ccp', mode: 'exact' },
      { path: 'workshop-areas', mode: 'exact' },
      { path: 'inspection-records', mode: 'exact' },
      { path: 'quality-inspection-tasks', mode: 'exact' },
    ],
    equipment_site: [
      { path: 'equipment', mode: 'exact' },
      { path: 'equipment/faults', mode: 'exact' },
      { path: 'equipment/stats', mode: 'exact' },
      { path: 'maintenance-plans', mode: 'exact' },
      { path: 'maintenance-records', mode: 'exact' },
      { path: 'environment-records', mode: 'exact' },
      { path: 'metal-detections', mode: 'exact' },
      { path: 'rework-records', mode: 'exact' },
      { path: 'waste', mode: 'exact' },
      { path: 'measuring-equipment', mode: 'exact' },
      { path: 'medication-records', mode: 'exact' },
      { path: 'cleaning-plans', mode: 'exact' },
      { path: 'cleaning-records', mode: 'exact' },
      { path: 'sanitizer-concentration-checks', mode: 'prefix' },
      { path: 'fragile-item-inspections', mode: 'exact' },
      { path: 'violation-records', mode: 'exact' },
      { path: 'visitor-records', mode: 'exact' },
      { path: 'emergency-drills', mode: 'exact' },
      { path: 'food-safety-culture-records', mode: 'exact' },
      { path: 'access-declarations', mode: 'prefix' },
      { path: 'laundry-records', mode: 'prefix' },
    ],
    traceability_batch: [
      { path: 'traceability', mode: 'exact' },
      { path: 'batch-trace', mode: 'exact' },
      { path: 'batch-trace/trace', mode: 'exact' },
      { path: 'batch-trace/material-batches', mode: 'exact' },
      { path: 'batch-trace/material-usage', mode: 'exact' },
      { path: 'warehouse/material-balance', mode: 'exact' },
      { path: 'warehouse/traceability', mode: 'exact' },
      { path: 'packaging-material-usages', mode: 'exact' },
      { path: 'incoming-inspections', mode: 'exact' },
    ],
    warehouse: [
      { path: 'warehouse/batches', mode: 'exact' },
      { path: 'warehouse/materials', mode: 'exact' },
      { path: 'warehouse/inbound', mode: 'exact' },
      { path: 'warehouse/requisitions', mode: 'exact' },
      { path: 'warehouse/staging-area', mode: 'exact' },
      { path: 'warehouse/suppliers', mode: 'exact' },
      { path: 'scraps', mode: 'exact' },
      { path: 'returns', mode: 'exact' },
      { path: 'external-parties', mode: 'exact' },
    ],
    training: [
      { path: 'training', mode: 'exact' },
      { path: 'training/records', mode: 'exact' },
      { path: 'training/archive', mode: 'exact' },
      { path: 'training/exam', mode: 'exact' },
      { path: 'training/questions', mode: 'exact' },
    ],
  },
};
