import { mount } from '@vue/test-utils';
import { describe, expect, it, vi } from 'vitest';
import BatchDetail from '../BatchDetail.vue';

vi.mock('vue-router', () => ({
  useRoute: () => ({ params: { id: 'prod-batch-1' } }),
  useRouter: () => ({ back: vi.fn(), push: vi.fn() }),
}));

vi.mock('@/stores/user', () => ({
  useUserStore: () => ({ user: { id: 'user-1' } }),
}));

vi.mock('@/api/batch', () => ({
  productionBatchApi: {
    getById: vi.fn().mockResolvedValue({
      id: 'prod-batch-1',
      batchNumber: 'PB-001',
      productName: '蛋糕',
      productCode: 'P001',
      quantity: 100,
      unit: 'kg',
      status: 'in_progress',
      recipeId: 'recipe-1',
      materialUsages: [],
      aggregations: [],
    }),
  },
  materialUsageApi: {
    getByBatch: vi.fn().mockResolvedValue([]),
  },
  batchMixingAggregationApi: {
    create: vi.fn(),
    confirm: vi.fn(),
  },
}));

vi.mock('@/api/request', () => ({
  default: {
    get: vi.fn().mockResolvedValue([]),
  },
}));

const stubs = {
  'el-page-header': { template: '<header />' },
  'el-card': { template: '<section><slot name="header" /><slot /></section>' },
  'el-tag': { template: '<span><slot /></span>' },
  'el-descriptions': { template: '<dl><slot /></dl>' },
  'el-descriptions-item': { template: '<dd><slot /></dd>' },
  'el-button': { template: '<button @click="$emit(\'click\')"><slot /></button>' },
  'el-table': { template: '<table><slot /></table>', props: ['data'] },
  'el-table-column': { template: '<td />' },
  'el-empty': { template: '<div />' },
  'el-dialog': { template: '<div><slot /><slot name="footer" /></div>' },
  'el-form': { template: '<form><slot /></form>' },
  'el-form-item': { template: '<div><slot /></div>' },
  'el-select': { template: '<select><slot /></select>' },
  'el-option': { template: '<option :value="value">{{ label }}</option>', props: ['value', 'label'] },
  'el-input': { template: '<input :placeholder="placeholder" />', props: ['placeholder'] },
  'el-input-number': { template: '<input type="number" />' },
};

describe('BatchDetail manual material-usage entry retired (Task 7)', () => {
  it('does not render any manual add-material affordance', async () => {
    const wrapper = mount(BatchDetail, { global: { stubs } });

    await Promise.resolve();
    await Promise.resolve();

    // Manual entry is retired: no "添加物料" button, no material-batch selector,
    // no free-text batch input. BatchMaterialUsage is auto-generated by the
    // mixing trace bridge.
    expect(wrapper.text()).not.toContain('添加物料');
    expect(wrapper.find('[data-test="material-batch-select"]').exists()).toBe(false);
    expect(wrapper.find('input[placeholder="请输入物料批次 ID"]').exists()).toBe(false);
    // The usage record panel still renders (read-only list).
    expect(wrapper.text()).toContain('物料使用记录');
  });
});
